Repository boostcamp-2020/Project18-A-Boostagram, pull requests merged in 2020-11, with the labels that each got.

#86 #67, #68, #69, #70, #73 - 프로젝트 초기 설정 및 구현
  .gitignore
  README.md
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.html
  client/src/index.js
  client/webpack.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/routes/index.ts
  server/src/services/index.ts
  server/tsconfig.json
Labels: chore

#87 1주차 배포
  .gitignore
  README.md
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.html
  client/src/index.js
  client/webpack.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/routes/index.ts
  server/src/services/index.ts
  server/tsconfig.json
Labels: BE, FE, chore

#90 #71 - MongoDB 설계
  server/env
  server/src/app.ts
  server/src/models/index.ts
  server/src/models/user.ts
  server/src/routes/index.ts
  server/src/routes/userRouter.ts
Labels: BE, refactor

#91 작업 환경 설정
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  client/.eslintrc.js
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.js
  server/.eslintrc.js
  server/.prettierrc
  server/env
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/models/index.ts
  server/src/models/user.ts
  server/src/routes/index.ts
  server/src/routes/userRouter.ts
Labels: chore

#92 #71 mongoose 스키마 설정
  server/.eslintrc.js
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/models/dm.model.ts
  server/src/models/feed.model.ts
  server/src/models/index.ts
  server/src/models/init.model.ts
  server/src/models/user.model.ts
  server/src/models/user.ts
  server/src/routes/index.ts
  server/src/routes/user.router.ts
Labels: BE, chore

#94 클라이언트 구조 설계
  client/.eslintrc.js
  client/src/App.js
  client/src/components/App.js
  client/src/components/common/Header.js
  client/src/components/newFeed/container/NewFeedContainer.js
  client/src/components/style/GlobalStyle.js
  client/src/components/style/Theme.js
  client/src/constants/path.js
  client/src/index.js
  client/webpack.config.js
Labels: FE, UI

#95 #18 - 게시글 작성 API
  server/src/controllers/feed.controller.ts
  server/src/models/feed.model.ts
  server/src/routes/feed.router.ts
  server/src/routes/index.ts
  server/src/routes/user.router.ts
  server/src/services/feed.service.ts
Labels: API, BE

#96 #82 - 상단바 UI 구현
  client/src/components/common/Header.js
  client/src/constants/icon.js
  client/src/constants/path.js
Labels: FE, UI

#99 #98 - 더미 데이터 seeding 구현
  server/src/models/init.model.ts
  server/src/routes/index.ts
  server/src/routes/user.router.ts
Labels: BE, chore

#100 #16 - 게시글 작성 UI
  .github/PULL_REQUEST_TEMPLATE.md
  client/package.json
  client/src/components/newFeed/container/NewFeedContainer.js
  client/src/components/newFeed/presentational/DisplayImg.js
  client/src/components/newFeed/presentational/InputFile.js
  client/src/components/newFeed/presentational/InputLocation.js
  client/src/components/newFeed/presentational/InputTag.js
  client/src/components/newFeed/presentational/InputText.js
  client/src/components/newFeed/presentational/SubmitButton.js
  client/src/components/style/Theme.js
  client/src/constants/path.js
  client/src/index.html
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/feed.controller.ts
Labels: FE, UI

#102 #4 탐색 페이지 UI 구현
  client/src/components/feedExplore/container/FeedExploreContainer.js
  client/src/components/feedExplore/presentational/FeedCard.js
  client/src/components/feedExplore/presentational/FeedList.js
  client/src/constants/icon.js
Labels: FE, UI
