Repository boostcamp-2020/Project18-A-Boostagram, pull requests merged in 2020-12, with the labels that each got.

#104 #6 - 탐색 페이지 조회 API 구현
  server/src/controllers/feed.controller.ts
  server/src/models/feed.model.ts
  server/src/models/init.model.ts
  server/src/routes/feed.router.ts
  server/src/services/feed.service.ts
Labels: API, BE, refactor

#105 #16 #21 게시글 작성 UI, 이미지 업로드 API 구현
  .gitignore
  client/src/components/App.js
  client/src/components/common/Header.js
  client/src/components/newFeed/container/NewFeedContainer.js
  client/src/components/newFeed/presentational/DisplayImg.js
  client/src/components/newFeed/presentational/ImgNav.js
  client/src/components/newFeed/presentational/InputFile.js
  client/src/components/newFeed/presentational/InputLocation.js
  client/src/components/newFeed/presentational/InputText.js
  client/src/components/newFeed/presentational/Profile.js
  client/src/constants/add.svg
  client/src/constants/path.js
  client/src/index.html
  server/env
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/routes/image.router.ts
  server/src/routes/index.ts
Labels: API, BE, FE, UI

#107 #84 홈 화면 UI 구현
  client/src/components/App.js
  client/src/components/feedExplore/dummy.js
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/Comment.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/Feed.js
  client/src/components/home/presentational/FeedItem.js
  client/src/components/home/presentational/Side.js
  client/src/components/home/presentational/Story.js
  client/src/components/home/presentational/StoryItems.js
  client/src/components/home/presentational/UserName.js
  client/src/constants/icon.js
  client/webpack.config.js
Labels: FE, UI

#109 #43 홈 화면 조회 API 구현
  client/package-lock.json
  client/package.json
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/Feed.js
  client/src/constants/path.js
  client/webpack.config.js
  server/src/controllers/feed.controller.ts
  server/src/models/feed.model.ts
  server/src/models/init.model.ts
  server/src/models/user.model.ts
  server/src/routes/feed.router.ts
  server/src/services/feed.service.ts
Labels: API, BE

#110 #75 - OAuth API 구현
  client/src/components/AouthTest.js
  client/src/components/App.js
  client/src/context/user.js
  client/webpack.config.js
  server/.eslintrc.js
  server/env
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/login.controller.ts
  server/src/models/init.model.ts
  server/src/models/user.model.ts
  server/src/passport/init.ts
  server/src/passport/token.generator.ts
  server/src/passport/valaidation.ts
  server/src/routes/index.ts
  server/src/routes/login.router.ts
  server/src/services/login.service.ts
Labels: API, BE

#111 #22, #27 - 사용자 프로필 화면 및 게시글 UI 구현
  client/src/components/App.js
  client/src/components/common/Header.js
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
  client/src/constants/icon.js
  client/src/constants/path.js
  client/webpack.config.js
Labels: FE, UI

#112 #4 탐색 페이지 UI 구현
  client/src/components/feedExplore/container/FeedExploreContainer.js
  client/src/components/feedExplore/presentational/FeedCard.js
  client/src/components/feedExplore/presentational/FeedList.js
  client/src/constants/path.js
Labels: FE, UI

#113 #75 OAuth API 구현
  client/src/components/App.js
  client/src/components/common/Header.js
  client/src/components/login/container/LoginContainer.js
  client/src/components/newFeed/container/NewFeedContainer.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/feed.controller.ts
  server/src/passport/init.ts
  server/src/routes/feed.router.ts
Labels: API, BE, FE

#114 #84 홈 화면 UI 구현
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/Feed.js
  server/src/controllers/feed.controller.ts
Labels: refactor

#115 #30, #31 - 사용자 정보 및 게시글 조회 API 구현
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
  client/src/constants/path.js
  server/src/controllers/feed.controller.ts
  server/src/controllers/user.controller.ts
  server/src/routes/index.ts
  server/src/routes/user.router.ts
  server/src/services/user.service.ts
Labels: API, BE, FE, UI

#116 #74 - 로그인 페이지 구현
  client/src/components/login/container/LoginContainer.js
  client/src/components/login/presentational/LoginButton.js
  client/src/components/login/presentational/LoginHeader.js
  client/src/components/style/Theme.js
  client/src/constants/icon.js
  client/webpack.config.js
Labels: FE, UI

#117 #84 홈 화면 UI 구현 / 버그 수정
  client/src/components/common/Header.js
  client/src/components/feedExplore/dummy.js
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/Feed.js
  client/src/components/home/presentational/FeedItem.js
  client/src/components/home/presentational/Side.js
  client/src/components/home/presentational/Story.js
  client/src/components/home/presentational/StoryItems.js
  server/src/controllers/feed.controller.ts
  server/src/routes/feed.router.ts
Labels: FE, UI, refactor

#118 #16 게시글 작성 UI 구현 - 프로필
  client/src/components/App.js
  client/src/components/feedExplore/container/FeedExploreContainer.js
  client/src/components/newFeed/container/NewFeedContainer.js
  client/src/components/newFeed/presentational/InputText.js
  client/src/components/newFeed/presentational/Profile.js
  client/src/components/newFeed/presentational/SubmitButton.js
  client/src/components/style/Theme.js
  client/src/constants/icon.js
  client/src/context/modal.js
Labels: FE, UI

#121 #120 - 새로고침시 발생하는 문제 제거
  client/src/components/App.js
  client/src/constants/path.js
  client/src/public/favicon.ico
  client/webpack.config.js
Labels: FE

#124 fix: modal bug fix
  client/src/components/App.js
  client/src/components/newFeed/container/NewFeedContainer.js
Labels: FE, UI, bug

#125 #66 - Jenkins 설정
  README.md
  client/src/components/login/container/LoginContainer.js
  client/src/constants/path.js
  server/env
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/login.controller.ts
  server/src/services/login.service.ts
Labels: BE, FE, chore

#126 3주차 최종 배포
  README.md
  client/src/components/App.js
  client/src/components/login/container/LoginContainer.js
  client/src/components/newFeed/container/NewFeedContainer.js
  client/src/constants/path.js
  server/env
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/login.controller.ts
  server/src/services/login.service.ts
Labels: BE, FE, bug, chore, doc

#127 style: 이미지 비율 조절
  client/src/components/feedExplore/presentational/FeedCard.js
Labels: FE, UI

#128 Style: 이미지 비율 조정
  README.md
  client/src/components/feedExplore/presentational/FeedCard.js
Labels: FE, UI

#131 #108 - newFeed UI 수정
  client/src/components/newFeed/container/NewFeedContainer.js
  client/src/components/newFeed/presentational/DisplayImg.js
  client/src/components/newFeed/presentational/ImgNav.js
  client/src/components/newFeed/presentational/InputFile.js
  client/src/components/newFeed/presentational/InputText.js
  client/src/components/newFeed/presentational/Profile.js
  client/src/components/newFeed/presentational/SubmitButton.js
  client/src/components/style/Theme.js
Labels: FE, UI

#134 #52 게시글 좋아요 API 구현
  server/src/controllers/feed.controller.ts
  server/src/lib/getUserId.ts
  server/src/models/feed.model.ts
  server/src/routes/feed.router.ts
  server/src/services/feed.service.ts
Labels: API, BE

#132 #47 댓글 등록 구현 / #51 댓글 작성 API : parent 속성으로 대댓글 구분
  client/src/components/feedExplore/container/FeedExploreContainer.js
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/FeedItem.js
  client/src/constants/path.js
  server/src/controllers/comment.controller.ts
  server/src/controllers/feed.controller.ts
  server/src/models/feed.model.ts
  server/src/routes/comment.router.ts
  server/src/routes/index.ts
  server/src/services/comment.service.ts
Labels: API, BE, FE, UI

#136 feat: 사용자 이름에 맞는 프로필 페이지 구현
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: FE, UI

#139 #138 - 프로필 페이지에서 사용자 변경 시 렌더링되지 않음
  client/src/components/profile/container/ProfileContainer.js
Labels: FE, bug

#140 feat: 좋아요 api 클라이언트 연결
  client/src/components/home/presentational/FeedItem.js
  client/src/constants/path.js
Labels: FE

#141 #133 - 프로필 페이지에서 글 작성 반영되도록 수정
  client/src/components/profile/container/ProfileContainer.js
  server/src/models/feed.model.ts
Labels: FE, bug

#142 #135 사용자 팔로우/언팔로우
  client/src/components/profile/presentational/ProfileInfo.js
  client/src/constants/path.js
  server/src/controllers/user.controller.ts
  server/src/models/user.model.ts
  server/src/routes/user.router.ts
  server/src/services/user.service.ts
Labels: API, BE, FE

#145 #23 #25 #26 - 추천 검색 드롭박스, api, 검색 결과(프로필 페이지 연결)
  client/src/components/common/Header.js
  client/src/components/search/container/SearchBar.js
  client/src/components/search/presentational/ClearIcon.js
  client/src/components/search/presentational/DropBox.js
  client/src/components/search/presentational/SearchIcon.js
  client/src/components/search/presentational/SearchInput.js
  client/src/constants/path.js
  client/src/constants/search.svg
  client/src/public/clear.png
  client/webpack.config.js
  server/src/controllers/search.controller.ts
  server/src/models/user.model.ts
  server/src/routes/index.ts
  server/src/routes/search.router.ts
  server/src/services/search.service.ts
Labels: API, BE, FE, UI

#148 #147 - 로그아웃 버튼
  client/src/components/App.js
  client/src/components/common/Header.js
  client/src/components/home/presentational/Logout.js
  client/src/components/home/presentational/Side.js
  client/src/constants/value.js
Labels: FE, UI

#152 #151 - 게시물 수
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
  server/src/models/user.model.ts
  server/src/services/feed.service.ts
Labels: BE, FE, bug

#146 #143 - 그랜드 크롱님의 코드 리뷰
  client/src/components/App.js
  client/src/components/home/presentational/FeedItem.js
  client/src/components/home/presentational/FeedItemAuthor.js
  client/src/components/home/presentational/FeedItemComment.js
  client/src/components/home/presentational/FeedItemContent.js
  client/src/components/home/presentational/FeedItemIcon.js
  client/src/components/home/presentational/FeedItemImg.js
  client/src/components/home/presentational/FeedItemInput.js
  client/src/components/style/GlobalStyle.js
Labels: refactor

#153 user 모델의 notiContents 스키마 수정
  server/src/models/user.model.ts
Labels: BE

#154 feat: 홈 화면 링크 기능 추가 및 css 수정
  client/src/components/home/presentational/Comment.js
  client/src/components/home/presentational/FeedItemAuthor.js
  client/src/components/home/presentational/FeedItemImg.js
  client/src/components/home/presentational/UserName.js
Labels: FE, UI

#156 #149 #155 - 검색 드롭박스에 높이제한 및 스크롤, 타입에러 수정
  client/src/components/search/presentational/DropBox.js
  server/src/models/user.model.ts
Labels: FE, UI, bug

#159 #5 #19 - 게시물 상세 정보 모달 구현
  client/src/components/App.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/feedDetail/presentational/CommentInput.js
  client/src/components/feedDetail/presentational/CommentItem.js
  client/src/components/feedDetail/presentational/LikeMenu.js
  client/src/components/feedExplore/presentational/FeedCard.js
  client/webpack.config.js
Labels: FE, UI

#158 #157 - 프로필에서 팔로워 팔로우 전의 데이터로 표시되는것 수정
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: FE, bug

#160 feat: 중복 follow 필터 기능 구현
  client/src/components/profile/presentational/ProfileInfo.js
  server/src/controllers/user.controller.ts
  server/src/lib/isExists.ts
  server/src/services/user.service.ts
Labels: BE, bug

#162 #161 - 상세화면 좋아요 기능동작
  client/src/components/common/FeedItemIcon.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/home/presentational/FeedItem.js
Labels: FE

#163 style: 상세보기 모달 및 기타 UI 수정
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/CommentInput.js
  client/src/components/feedDetail/presentational/CommentItem.js
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/FeedItem.js
  client/src/components/home/presentational/FeedItemContent.js
  client/src/components/home/presentational/Story.js
  client/src/components/login/container/LoginContainer.js
  client/src/components/login/presentational/LoginHeader.js
  client/src/constants/icon.js
  client/src/public/favicon_duck.ico
  client/webpack.config.js
Labels: FE, UI

#164 fix: 팔로우/팔로잉 버그 수정
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: bug

#165 Week4 최종 배포
  client/src/api/ExploreFeedAPI.js
  client/src/api/HomeFeedAPI.js
  client/src/api/ProfileFeedAPI.js
  client/src/components/App.js
  client/src/components/common/FeedItemIcon.js
  client/src/components/common/Header.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/feedDetail/presentational/CommentInput.js
  client/src/components/feedDetail/presentational/CommentItem.js
  client/src/components/feedDetail/presentational/LikeMenu.js
  client/src/components/feedExplore/container/FeedExploreContainer.js
  client/src/components/feedExplore/presentational/FeedCard.js
  client/src/components/feedExplore/presentational/FeedList.js
  client/src/components/home/container/HomeContainer.js
  client/src/components/home/presentational/Comment.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/Feed.js
  client/src/components/home/presentational/FeedItem.js
  client/src/components/home/presentational/FeedItemAuthor.js
  client/src/components/home/presentational/FeedItemComment.js
  client/src/components/home/presentational/FeedItemContent.js
  client/src/components/home/presentational/FeedItemImg.js
  client/src/components/home/presentational/FeedItemInput.js
  client/src/components/home/presentational/Logout.js
  client/src/components/home/presentational/Side.js
  client/src/components/home/presentational/Story.js
  client/src/components/home/presentational/UserName.js
  client/src/components/login/container/LoginContainer.js
  client/src/components/login/presentational/LoginHeader.js
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
  client/src/components/search/container/SearchBar.js
  client/src/components/search/presentational/ClearIcon.js
  client/src/components/search/presentational/DropBox.js
  client/src/components/search/presentational/SearchIcon.js
  client/src/components/search/presentational/SearchInput.js
  client/src/components/style/GlobalStyle.js
  client/src/constants/icon.js
  client/src/constants/path.js
  client/src/constants/search.svg
  client/src/constants/value.js
  client/src/hooks/Intersection.js
  client/src/public/clear.png
  client/src/public/favicon_duck.ico
  client/src/utils/excuteTime.js
  client/webpack.config.js
  server/src/controllers/feed.controller.ts
  server/src/controllers/search.controller.ts
  server/src/controllers/user.controller.ts
  server/src/lib/isExists.ts
  server/src/models/feed.model.ts
  server/src/models/user.model.ts
  server/src/routes/index.ts
  server/src/routes/search.router.ts
  server/src/routes/user.router.ts
  server/src/services/feed.service.ts
  server/src/services/search.service.ts
  server/src/services/user.service.ts
Labels: chore

#167 chore: README.md 업데이트
  README.md
Labels: chore

#169 Hotfix
  client/src/components/feedDetail/presentational/CommentInput.js
  client/src/components/home/presentational/FeedItemContent.js
Labels: UI, bug

#171 Hotfix
  client/src/components/common/FeedItemIcon.js
  client/src/components/newFeed/presentational/ImgNav.js
Labels: FE, bug

#173 doc: readme 및 favicon 수정
  README.md
  client/src/public/favicon_B.ico
  client/src/public/favicon_B_nobg.ico
  client/webpack.config.js
Labels: doc

#175 fix: 홈 css 수정
  client/src/components/home/presentational/Comment.js
  client/src/components/home/presentational/UserName.js
Labels: UI

#176 fix: api 응답 수정
  server/src/controllers/comment.controller.ts
  server/src/controllers/feed.controller.ts
  server/src/controllers/user.controller.ts
Labels: API

#177 refactor: 예외처리
  server/src/controllers/login.controller.ts
  server/src/routes/image.router.ts
Labels: API, BE, refactor

#178 5주차 배포#1
  README.md
  client/src/components/home/presentational/Comment.js
  client/src/components/home/presentational/UserName.js
  client/src/public/favicon_B.ico
  client/src/public/favicon_B_nobg.ico
  client/webpack.config.js
  server/src/controllers/comment.controller.ts
  server/src/controllers/feed.controller.ts
  server/src/controllers/login.controller.ts
  server/src/controllers/user.controller.ts
  server/src/routes/image.router.ts
Labels: API, doc

#179 fix: 팔로우 이슈 해결
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: FE, bug

#180 fix: 좋아요 중복 이슈 backend fix
  server/src/lib/isExists.ts
  server/src/models/feed.model.ts
  server/src/services/feed.service.ts
Labels: bug

#181 feat: 게시물 상세 정보 조회 api 구현
  server/src/controllers/feed.controller.ts
  server/src/lib/isExists.ts
  server/src/models/feed.model.ts
  server/src/routes/feed.router.ts
  server/src/services/feed.service.ts
Labels: API, BE

#182 #172 - 상세보기 모달의 데이터 갱신 문제
  client/src/api/GetOneFeedAPI.js
  client/src/components/common/FeedItemIcon.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedExplore/presentational/FeedCard.js
  server/src/controllers/feed.controller.ts
  server/src/routes/feed.router.ts
  server/src/services/feed.service.ts
Labels: FE, bug

#184 fix: explore 서버 에러 이슈 해결 및 상세화면 링크 기능 추가
  client/src/api/GetOneFeedAPI.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/feedDetail/presentational/CommentItem.js
  client/src/components/profile/container/ProfileContainer.js
  client/src/constants/path.js
  server/src/routes/feed.router.ts
Labels: BE, FE, bug

#185 5주차 배포#2
  client/src/api/GetOneFeedAPI.js
  client/src/components/common/FeedItemIcon.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/feedDetail/presentational/CommentItem.js
  client/src/components/feedExplore/presentational/FeedCard.js
  client/src/components/profile/container/ProfileContainer.js
  client/src/components/profile/presentational/ProfileInfo.js
  client/src/constants/path.js
  server/src/controllers/feed.controller.ts
  server/src/lib/isExists.ts
  server/src/models/feed.model.ts
  server/src/routes/feed.router.ts
  server/src/services/feed.service.ts
Labels: API, BE, FE, bug

#187 fix: 팔로우 버그 수정
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: bug

#188 fix: 팔로우 버그 수정
  client/src/components/profile/presentational/ProfileInfo.js
Labels: bug

#189 5주차 배포#3
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: FE, bug

#183 feat: 좋아요 클릭 시 서버, 클라이언트 간 소켓 통신 구현
  client/package-lock.json
  client/package.json
  client/src/components/App.js
  client/src/components/common/FeedItemIcon.js
  client/src/context/socket.js
  client/src/utils/notiEvent.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/lib/notiEvent.ts
Labels: BE, FE

#190 홈 팔로우 목록 부분 수정 및 팔로우 클릭 기능 추가
  client/src/components/common/Header.js
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/Story.js
  client/src/components/home/presentational/StoryItems.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: FE, UI

#191 feat: 클라이언트 소켓 연결 시 확인하지 않은 알림 수 전송
  client/src/utils/notiEvent.js
  server/src/lib/notiEvent.ts
  server/src/services/user.service.ts
Labels: API, BE

#192 #8 - push알림 UI
  client/src/components/App.js
  client/src/components/common/Header.js
  client/src/components/style/Theme.js
  client/src/constants/icon.js
  client/src/utils/notiEvent.js
  server/src/lib/notiEvent.ts
Labels: FE, UI

#195 #7 알림 내역 ui
  client/src/components/common/Header.js
  client/src/components/notiHistory/container/NotiHistoryContainer.js
  client/src/components/notiHistory/presentational/DropBox.js
Labels: FE, UI

#197 feat: 좋아요 시 DB에 알림 저장
  server/src/lib/notiEvent.ts
  server/src/models/user.model.ts
  server/src/services/user.service.ts
Labels: API, BE

#193 #194 - lazy load 및 애니메이션
  client/package-lock.json
  client/package.json
  client/src/components/feedExplore/presentational/FeedCard.js
  client/src/components/feedExplore/presentational/LazyImage.js
Labels: FE

#198 #9 알림 내역 조회 API
  server/src/controllers/user.controller.ts
  server/src/models/user.model.ts
  server/src/routes/user.router.ts
  server/src/services/user.service.ts
Labels: API, BE

#199 feat: 알림 내역 api 연결 및 버그 수정
  README.md
  client/src/components/App.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/notiHistory/presentational/DropBox.js
  client/src/constants/path.js
  client/src/utils/notiEvent.js
Labels: FE, UI, bug

#200 5주차 배포#4
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/App.js
  client/src/components/common/FeedItemIcon.js
  client/src/components/common/Header.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/AuthorProfile.js
  client/src/components/feedExplore/presentational/FeedCard.js
  client/src/components/feedExplore/presentational/LazyImage.js
  client/src/components/home/presentational/Contents.js
  client/src/components/home/presentational/Story.js
  client/src/components/home/presentational/StoryItems.js
  client/src/components/notiHistory/container/NotiHistoryContainer.js
  client/src/components/notiHistory/presentational/DropBox.js
  client/src/components/profile/presentational/ProfileInfo.js
  client/src/components/style/Theme.js
  client/src/constants/icon.js
  client/src/constants/path.js
  client/src/context/socket.js
  client/src/utils/notiEvent.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/user.controller.ts
  server/src/lib/notiEvent.ts
  server/src/models/user.model.ts
  server/src/routes/user.router.ts
  server/src/services/user.service.ts
Labels: API, BE, FE, UI, bug

#201 fix: 잘못된 대상에게 알림이 전송되는 버그 수정
  server/src/lib/notiEvent.ts
Labels: BE, bug

#205 feat: 알림 도착 시간 출력 / #202 알림 없을 때 회색박스 렌더링됨
  client/src/components/notiHistory/presentational/DropBox.js
  server/src/models/user.model.ts
  server/src/services/user.service.ts
Labels: BE, FE, UI

#207 #206 코멘트 작성 시간 출력
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/CommentItem.js
Labels: FE, UI

#204 #203 - 로그인 페이지에서 발생하는 warning 해결
  client/src/components/App.js
Labels: FE, bug

#208 5주차 배포 #5
  client/src/components/App.js
  client/src/components/feedDetail/container/FeedDetailContainer.js
  client/src/components/feedDetail/presentational/CommentItem.js
  client/src/components/notiHistory/presentational/DropBox.js
  client/src/constants/path.js
  server/src/models/user.model.ts
  server/src/services/user.service.ts
Labels: FE, UI, bug, chore

#209 5주차 배포 #6
  server/src/services/user.service.ts
Labels: BE, bug

#211 5주차 배포#7
  client/src/components/notiHistory/presentational/DropBox.js
  client/src/components/profile/presentational/ProfileInfo.js
Labels: FE, UI

#212 5주차 최종 배포 #8
  client/src/components/feedDetail/container/FeedDetailContainer.js
Labels: bug

#213 doc: update README.md
  README.md
Labels: doc
